DOCS-8368 adding additional information on policy properties. Rewriti…
mulesoft/docs-anypoint-security pull request #51
Opened 2020-08-07 22:28 UTC by sleslie23

DOCS-8368 adding additional information on policy properties. Rewriting intro paragraphs for SEO optimization.

2020-08-11 21:26 UTC, clies212 requested changes

2020-08-11 21:26 UTC, clies212 commented on modules/ROOT/pages/cap-policy.adoc
> +Anypoint Security uses the HTTP Limits policy to prevent an attacker from sending large messages that can consume bandwidth and result performance degradation or system outage. This policy applies to
This looks a bit dicey: "large messages that can consume bandwidth and result performance degradation or system outage". Maybe something like: "large messages that can consume bandwidth which can cause performance degradation or denial of service."

2020-08-11 21:26 UTC, clies212 commented on modules/ROOT/pages/cap-policy.adoc
> +The HTTP Limits policy limts the size of TCP protocol messages, paths, headers, and footers. This policy does not perform checks on the content of a message.
Spelling mistake: "limts". Should be "limits".

2020-08-11 21:26 UTC, clies212 commented on modules/ROOT/pages/cap-policy.adoc
> +If the request body scanning option is enabled, do not set this value to a value larger than required to prevent attackers from abusing request body checking and exhausting resources.
Delete "If the request body scanning option is enabled,". This text makes sense in the context of the WAF policy but is confusing when it only applies to the Limits policy. The sentence seems OK without that leading prepositional phrase from a technical content point of view.

2021-09-24 18:16 UTC, IsaacEldridge commented
Closing this PR against https://github.com/mulesoft/docs-anypoint-security/pull/62 which is an updated duplicate

2021-09-24 18:16 UTC, closed without merging